### ISSUE TITLE
Can't Login

### ISSUE THREAD

**Issue by Lavanmark** [cs340tabyu/cs340Winter2017#1077]
I can register a new user and see the list of games but when I "log out" by returning to the login screen using the back button, I can't login. Clicking the login button gives no message popup or anything to state that there is an error. It also seems that the server never receives a login message or anything of the sort.

**Comment by Lavanmark** [comment]
`03-31 18:26:00.614 7054-7054/com.thamj.cs340.tickettoride I/System.out: -------------------------
03-31 18:26:00.614 7054-7054/com.thamj.cs340.tickettoride I/System.out: Sending command...
03-31 18:26:00.614 7054-7054/com.thamj.cs340.tickettoride I/System.out: 	methodName: login
03-31 18:26:00.614 7054-7054/com.thamj.cs340.tickettoride I/System.out: 	commandIndex: -1 userId: asdf gameId: null
03-31 18:26:00.616 7054-7054/com.thamj.cs340.tickettoride W/System.err: java.lang.NumberFormatException: For input string: "android.support.v7.widget.AppCompatEditText{9c690b2 VFED..CL. ........ 0,22-400,113 #7f0d008b app:id/edit_text_port_number}"
03-31 18:26:00.617 7054-7054/com.thamj.cs340.tickettoride W/System.err:     at java.lang.Integer.parseInt(Integer.java:521)
03-31 18:26:00.617 7054-7054/com.thamj.cs340.tickettoride W/System.err:     at java.lang.Integer.parseInt(Integer.java:556)
03-31 18:26:00.617 7054-7054/com.thamj.cs340.tickettoride W/System.err:     at com.thamj.cs340.tickettoride.client.network.ClientCommunicator.setPort(ClientCommunicator.java:168)
03-31 18:26:00.617 7054-7054/com.thamj.cs340.tickettoride W/System.err:     at com.thamj.cs340.tickettoride.client.network.ServerProxy.setPort(ServerProxy.java:201)
03-31 18:26:00.617 7054-7054/com.thamj.cs340.tickettoride W/System.err:     at com.thamj.cs340.tickettoride.client.UIFacade.setPort(UIFacade.java:400)
03-31 18:26:00.617 7054-7054/com.thamj.cs340.tickettoride W/System.err:     at com.thamj.cs340.tickettoride.client.presenter.LoginRegisterPresenter.setPort(LoginRegisterPresenter.java:84)
03-31 18:26:00.617 7054-7054/com.thamj.cs340.tickettoride W/System.err:     at com.thamj.cs340.tickettoride.client.view.LoginRegisterActivity$1.onClick(LoginRegisterActivity.java:73)
03-31 18:26:00.617 7054-7054/com.thamj.cs340.tickettoride W/System.err:     at android.view.View.performClick(View.java:5637)
03-31 18:26:00.617 7054-7054/com.thamj.cs340.tickettoride W/System.err:     at android.view.View$PerformClick.run(View.java:22429)
03-31 18:26:00.617 7054-7054/com.thamj.cs340.tickettoride W/System.err:     at android.os.Handler.handleCallback(Handler.java:751)
03-31 18:26:00.617 7054-7054/com.thamj.cs340.tickettoride W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
03-31 18:26:00.617 7054-7054/com.thamj.cs340.tickettoride W/System.err:     at android.os.Looper.loop(Looper.java:154)
03-31 18:26:00.617 7054-7054/com.thamj.cs340.tickettoride W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6119)
03-31 18:26:00.617 7054-7054/com.thamj.cs340.tickettoride W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
03-31 18:26:00.617 7054-7054/com.thamj.cs340.tickettoride W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
03-31 18:26:00.617 7054-7054/com.thamj.cs340.tickettoride W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
03-31 18:26:00.617 7054-7054/com.thamj.cs340.tickettoride I/System.out: For input string: "android.support.v7.widget.AppCompatEditText{9c690b2 VFED..CL. ........ 0,22-400,113 #7f0d008b app:id/edit_text_port_number}"
03-31 18:26:00.640 7054-7281/com.thamj.cs340.tickettoride D/NetworkSecurityConfig: No Network Security Config specified, using platform default
03-31 18:26:00.646 7054-7281/com.thamj.cs340.tickettoride W/System.err: java.net.UnknownHostException: Invalid host: http://android.support.v7.widget.AppCompatEditText{54e0803 VFED..CL. ........ 0,22-400,113 #7f0d008a app:id/edit_text_ip_address}:3000/auth
03-31 18:26:00.646 7054-7281/com.thamj.cs340.tickettoride W/System.err:     at com.android.okhttp.HttpUrl.getChecked(HttpUrl.java:674)
03-31 18:26:00.646 7054-7281/com.thamj.cs340.tickettoride W/System.err:     at com.android.okhttp.OkHttpClient$1.getHttpUrlChecked(OkHttpClient.java:165)
03-31 18:26:00.646 7054-7281/com.thamj.cs340.tickettoride W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.newHttpEngine(HttpURLConnectionImpl.java:345)
03-31 18:26:00.646 7054-7281/com.thamj.cs340.tickettoride W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.initHttpEngine(HttpURLConnectionImpl.java:331)
03-31 18:26:00.646 7054-7281/com.thamj.cs340.tickettoride W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:123)
03-31 18:26:00.646 7054-7281/com.thamj.cs340.tickettoride W/System.err:     at com.thamj.cs340.tickettoride.client.network.ClientCommunicator$SendTask.doInBackground(ClientCommunicator.java:192)
03-31 18:26:00.646 7054-7281/com.thamj.cs340.tickettoride W/System.err:     at com.thamj.cs340.tickettoride.client.network.ClientCommunicator$SendTask.doInBackground(ClientCommunicator.java:178)
03-31 18:26:00.646 7054-7281/com.thamj.cs340.tickettoride W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:305)
03-31 18:26:00.647 7054-7281/com.thamj.cs340.tickettoride W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
03-31 18:26:00.647 7054-7281/com.thamj.cs340.tickettoride W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
03-31 18:26:00.647 7054-7281/com.thamj.cs340.tickettoride W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
03-31 18:26:00.647 7054-7281/com.thamj.cs340.tickettoride W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
03-31 18:26:00.647 7054-7281/com.thamj.cs340.tickettoride W/System.err:     at java.lang.Thread.run(Thread.java:761)`

**Comment by Lavanmark** [comment]
> 03-31 18:26:00.614 7054-7054/com.thamj.cs340.tickettoride I/System.out: -------------------------
03-31 18:26:00.614 7054-7054/com.thamj.cs340.tickettoride I/System.out: Sending command...
03-31 18:26:00.614 7054-7054/com.thamj.cs340.tickettoride I/System.out: 	methodName: login
03-31 18:26:00.614 7054-7054/com.thamj.cs340.tickettoride I/System.out: 	commandIndex: -1 userId: asdf gameId: null
03-31 18:26:00.616 7054-7054/com.thamj.cs340.tickettoride W/System.err: java.lang.NumberFormatException: For input string: "android.support.v7.widget.AppCompatEditText{9c690b2 VFED..CL. ........ 0,22-400,113 #7f0d008b app:id/edit_text_port_number}"
03-31 18:26:00.617 7054-7054/com.thamj.cs340.tickettoride W/System.err:     at java.lang.Integer.parseInt(Integer.java:521)
03-31 18:26:00.617 7054-7054/com.thamj.cs340.tickettoride W/System.err:     at java.lang.Integer.parseInt(Integer.java:556)
03-31 18:26:00.617 7054-7054/com.thamj.cs340.tickettoride W/System.err:     at com.thamj.cs340.tickettoride.client.network.ClientCommunicator.setPort(ClientCommunicator.java:168)
03-31 18:26:00.617 7054-7054/com.thamj.cs340.tickettoride W/System.err:     at com.thamj.cs340.tickettoride.client.network.ServerProxy.setPort(ServerProxy.java:201)
03-31 18:26:00.617 7054-7054/com.thamj.cs340.tickettoride W/System.err:     at com.thamj.cs340.tickettoride.client.UIFacade.setPort(UIFacade.java:400)
03-31 18:26:00.617 7054-7054/com.thamj.cs340.tickettoride W/System.err:     at com.thamj.cs340.tickettoride.client.presenter.LoginRegisterPresenter.setPort(LoginRegisterPresenter.java:84)
03-31 18:26:00.617 7054-7054/com.thamj.cs340.tickettoride W/System.err:     at com.thamj.cs340.tickettoride.client.view.LoginRegisterActivity$1.onClick(LoginRegisterActivity.java:73)
03-31 18:26:00.617 7054-7054/com.thamj.cs340.tickettoride W/System.err:     at android.view.View.performClick(View.java:5637)
03-31 18:26:00.617 7054-7054/com.thamj.cs340.tickettoride W/System.err:     at android.view.View$PerformClick.run(View.java:22429)
03-31 18:26:00.617 7054-7054/com.thamj.cs340.tickettoride W/System.err:     at android.os.Handler.handleCallback(Handler.java:751)
03-31 18:26:00.617 7054-7054/com.thamj.cs340.tickettoride W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
03-31 18:26:00.617 7054-7054/com.thamj.cs340.tickettoride W/System.err:     at android.os.Looper.loop(Looper.java:154)
03-31 18:26:00.617 7054-7054/com.thamj.cs340.tickettoride W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6119)
03-31 18:26:00.617 7054-7054/com.thamj.cs340.tickettoride W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
03-31 18:26:00.617 7054-7054/com.thamj.cs340.tickettoride W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
03-31 18:26:00.617 7054-7054/com.thamj.cs340.tickettoride W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
03-31 18:26:00.617 7054-7054/com.thamj.cs340.tickettoride I/System.out: For input string: "android.support.v7.widget.AppCompatEditText{9c690b2 VFED..CL. ........ 0,22-400,113 #7f0d008b app:id/edit_text_port_number}"
03-31 18:26:00.640 7054-7281/com.thamj.cs340.tickettoride D/NetworkSecurityConfig: No Network Security Config specified, using platform default
03-31 18:26:00.646 7054-7281/com.thamj.cs340.tickettoride W/System.err: java.net.UnknownHostException: Invalid host: http://android.support.v7.widget.AppCompatEditText{54e0803 VFED..CL. ........ 0,22-400,113 #7f0d008a app:id/edit_text_ip_address}:3000/auth
03-31 18:26:00.646 7054-7281/com.thamj.cs340.tickettoride W/System.err:     at com.android.okhttp.HttpUrl.getChecked(HttpUrl.java:674)
03-31 18:26:00.646 7054-7281/com.thamj.cs340.tickettoride W/System.err:     at com.android.okhttp.OkHttpClient$1.getHttpUrlChecked(OkHttpClient.java:165)
03-31 18:26:00.646 7054-7281/com.thamj.cs340.tickettoride W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.newHttpEngine(HttpURLConnectionImpl.java:345)
03-31 18:26:00.646 7054-7281/com.thamj.cs340.tickettoride W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.initHttpEngine(HttpURLConnectionImpl.java:331)
03-31 18:26:00.646 7054-7281/com.thamj.cs340.tickettoride W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:123)
03-31 18:26:00.646 7054-7281/com.thamj.cs340.tickettoride W/System.err:     at com.thamj.cs340.tickettoride.client.network.ClientCommunicator$SendTask.doInBackground(ClientCommunicator.java:192)
03-31 18:26:00.646 7054-7281/com.thamj.cs340.tickettoride W/System.err:     at com.thamj.cs340.tickettoride.client.network.ClientCommunicator$SendTask.doInBackground(ClientCommunicator.java:178)
03-31 18:26:00.646 7054-7281/com.thamj.cs340.tickettoride W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:305)
03-31 18:26:00.647 7054-7281/com.thamj.cs340.tickettoride W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
03-31 18:26:00.647 7054-7281/com.thamj.cs340.tickettoride W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
03-31 18:26:00.647 7054-7281/com.thamj.cs340.tickettoride W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
03-31 18:26:00.647 7054-7281/com.thamj.cs340.tickettoride W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
03-31 18:26:00.647 7054-7281/com.thamj.cs340.tickettoride W/System.err:     at java.lang.Thread.run(Thread.java:761)

**Comment by Lavanmark** [comment]
That is the console of your app when you try to log a valid user in.

**Comment by joshuakcockrell** [comment]
Fixed. We were grabbing the actual UI button's toString(), not getText().toString()
