### ISSUE TITLE
When I did a game with all AI and finished the set up rounds, the first time I tried rolling it started a rolling loop and gave me this exception:

### ISSUE THREAD

**Issue by MCTWalker** [cs340tabyu/cs340Winter2017#658]
java.lang.NullPointerException
        at shared.model.resources.Bank.getResource(Bank.java:67)
        at shared.model.map.Map.getResources(Map.java:703)
        at shared.model.map.Map.harvestResources(Map.java:684)
        at server.facade.MovesFacade.rollNumber(MovesFacade.java:66)
        at server.commands.MovesRollNumber.serverExecute(MovesRollNumber.java:29)
        at server.handlers.BaseHandler.handle(BaseHandler.java:75)
        at server.handlers.JoinedGameHandler.handle(JoinedGameHandler.java:81)
        at com.sun.net.httpserver.Filter$Chain.doFilter(Unknown Source)
        at sun.net.httpserver.AuthFilter.doFilter(Unknown Source)
        at com.sun.net.httpserver.Filter$Chain.doFilter(Unknown Source)
        at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(Unknown Source)
        at com.sun.net.httpserver.Filter$Chain.doFilter(Unknown Source)
        at sun.net.httpserver.ServerImpl$Exchange.run(Unknown Source)
        at sun.net.httpserver.ServerImpl$DefaultExecutor.execute(Unknown Source)
        at sun.net.httpserver.ServerImpl$Dispatcher.handle(Unknown Source)
        at sun.net.httpserver.ServerImpl$Dispatcher.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

**Comment by MCTWalker** [comment]
Team 15 P3

**Comment by csydvs** [comment]
see #540
