### ISSUE TITLE
Stuck in RollingState

### ISSUE THREAD

**Issue by jjaywhitaker** [cs340tabyu/cs340Winter2017#700]
Stuck in rolling state. Finished my turn and when it became my turn again the button said "Rolling" but the modal didn't pop up for me to roll. 
It also came up as a NullPointerException in the RollController
Here is the pertinent part of the stack trace
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
        at client.roll.RollController.rollDice(RollController.java:88)
        at client.roll.RollView$1.actionPerformed(RollView.java:74)
        at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)

**Comment by Chroniclerz** [comment]
Were you playing with AI's?

**Comment by Chroniclerz** [comment]
Resolved.
