### ISSUE TITLE
Can't create game, no games to join

### ISSUE THREAD

**Issue by UnoriginalElephant** [cs340tabyu/cs340Winter2017#724]
Creating a game doesn't work, and there are no games to join, so there's nothing to test.  Email someone from Team 9 ASAP with something that works, even if it just has a hard-coded default game like the demo.  TAs said this should be P1 if there's nothing for us to test, sorry :(

**Comment by UnoriginalElephant** [comment]
Here's the stack trace from the server when I login:

```
Nov 18, 2016 2:38:27 PM server.Server init
INFO: Initializing Server
USERNAME: Sam
PASSWORD: sam
Nov 18, 2016 2:38:50 PM server.handler.ServerHandler handle
INFO: Request: /user/login
Internal Server Error
java.lang.Exception
        at server.serverCommand.user.LoginCommand.execute(LoginCommand.java:61)
        at server.handler.ServerHandler.handle(ServerHandler.java:45)
        at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
        at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
        at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
        at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:675)
        at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
        at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:647)
        at sun.net.httpserver.ServerImpl$DefaultExecutor.execute(ServerImpl.java:158)
        at sun.net.httpserver.ServerImpl$Dispatcher.handle(ServerImpl.java:431)
        at sun.net.httpserver.ServerImpl$Dispatcher.run(ServerImpl.java:396)
        at java.lang.Thread.run(Thread.java:745)
Nov 18, 2016 2:38:50 PM server.handler.ServerHandler handle
INFO: Request: /games/list
java.lang.NullPointerException
        at server.handler.ServerHandler.handle(ServerHandler.java:52)
        at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
        at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
        at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
        at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:675)
        at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
        at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:647)
        at sun.net.httpserver.ServerImpl$DefaultExecutor.execute(ServerImpl.java:158)
        at sun.net.httpserver.ServerImpl$Dispatcher.handle(ServerImpl.java:431)
        at sun.net.httpserver.ServerImpl$Dispatcher.run(ServerImpl.java:396)
        at java.lang.Thread.run(Thread.java:745)
Nov 18, 2016 2:38:50 PM server.handler.ServerHandler handle
SEVERE: Bad Request: null
Nov 18, 2016 2:38:51 PM server.handler.ServerHandler handle
INFO: Request: /games/list
java.lang.NullPointerException                                                                                                   
        at server.handler.ServerHandler.handle(ServerHandler.java:52)                                                            
        at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)                                                          
        at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)                                                            
        at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)                                                          
        at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:675)                                        
        at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)                                                          
        at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:647)                                                       
        at sun.net.httpserver.ServerImpl$DefaultExecutor.execute(ServerImpl.java:158)                                            
        at sun.net.httpserver.ServerImpl$Dispatcher.handle(ServerImpl.java:431)                                                  
        at sun.net.httpserver.ServerImpl$Dispatcher.run(ServerImpl.java:396)                                                     
        at java.lang.Thread.run(Thread.java:745)                                                                                 
Nov 18, 2016 2:38:51 PM server.handler.ServerHandler handle                                                                      
SEVERE: Bad Request: null  
```

**Comment by UnoriginalElephant** [comment]
Here's what shows up on the client:

```
java.net.ConnectException: doGetCommand failed... /games/list (http code 400)
        at server.ServerProxy.doGetCommand(ServerProxy.java:991)
        at server.ServerProxy.gameList(ServerProxy.java:152)
        at client.join.JoinGameController.start(JoinGameController.java:124)
        at client.main.Catan$1$2.execute(Catan.java:102)
        at client.login.LoginController.signIn(LoginController.java:92)
        at client.login.LoginView$SignInPanel$1.actionPerformed(LoginView.java:268)
        at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
        at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
        at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
        at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
        at javax.swing.plaf.basic.BasicButtonListener$Actions.actionPerformed(BasicButtonListener.java:303)
        at javax.swing.SwingUtilities.notifyAction(SwingUtilities.java:1663)
        at javax.swing.JComponent.processKeyBinding(JComponent.java:2882)
        at javax.swing.JComponent.processKeyBindings(JComponent.java:2929)
        at javax.swing.JComponent.processKeyEvent(JComponent.java:2845)
        at java.awt.Component.processEvent(Component.java:6310)
        at java.awt.Container.processEvent(Container.java:2236)
        at java.awt.Component.dispatchEventImpl(Component.java:4889)
        at java.awt.Container.dispatchEventImpl(Container.java:2294)
        at java.awt.Component.dispatchEvent(Component.java:4711)
        at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1954)
        at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:806)
        at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1074)
        at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:945)
        at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:771)
        at java.awt.Component.dispatchEventImpl(Component.java:4760)
        at java.awt.Container.dispatchEventImpl(Container.java:2294)
        at java.awt.Window.dispatchEventImpl(Window.java:2746)
        at java.awt.Component.dispatchEvent(Component.java:4711)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.awt.EventQueue$4.run(EventQueue.java:731)
        at java.awt.EventQueue$4.run(EventQueue.java:729)                                                                        
        at java.security.AccessController.doPrivileged(Native Method)                                                            
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)               
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)                                                                
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)                                     
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)                                        
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)                                     
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)                                                 
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)                                                  
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)                                                         
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException                                                            
        at java.io.StringReader.<init>(StringReader.java:50)                                                                     
        at com.google.gson.JsonParser.parse(JsonParser.java:45)                                                                  
        at server.ServerProxy.gameList(ServerProxy.java:155)                                                                     
        at client.join.JoinGameController.start(JoinGameController.java:124)                                                     
        at client.main.Catan$1$2.execute(Catan.java:102)                                                                         
        at client.login.LoginController.signIn(LoginController.java:92)                                                          
        at client.login.LoginView$SignInPanel$1.actionPerformed(LoginView.java:268)                                              
        at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)                                              
        at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)                                          
        at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)                                       
        at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)                                                
        at javax.swing.plaf.basic.BasicButtonListener$Actions.actionPerformed(BasicButtonListener.java:303)                      
        at javax.swing.SwingUtilities.notifyAction(SwingUtilities.java:1663)                                                     
        at javax.swing.JComponent.processKeyBinding(JComponent.java:2882)                                                        
        at javax.swing.JComponent.processKeyBindings(JComponent.java:2929)                                                       
        at javax.swing.JComponent.processKeyEvent(JComponent.java:2845)                                                          
        at java.awt.Component.processEvent(Component.java:6310)                                                                  
        at java.awt.Container.processEvent(Container.java:2236)                                                                  
        at java.awt.Component.dispatchEventImpl(Component.java:4889)                                                             
        at java.awt.Container.dispatchEventImpl(Container.java:2294)                                                             
        at java.awt.Component.dispatchEvent(Component.java:4711)                                                                 
        at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1954)
        at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:806)
        at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1074)
        at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:945)
        at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:771)
        at java.awt.Component.dispatchEventImpl(Component.java:4760)
        at java.awt.Container.dispatchEventImpl(Container.java:2294)
        at java.awt.Window.dispatchEventImpl(Window.java:2746)
        at java.awt.Component.dispatchEvent(Component.java:4711)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.awt.EventQueue$4.run(EventQueue.java:731)
        at java.awt.EventQueue$4.run(EventQueue.java:729)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
1 second/s
java.net.ConnectException: doGetCommand failed... /games/list (http code 400)
        at server.ServerProxy.doGetCommand(ServerProxy.java:991)
        at server.ServerProxy.gameList(ServerProxy.java:152)
        at server.ServerPoller$1.run(ServerPoller.java:48)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)
Exception in thread "Timer-0" java.lang.NullPointerException
        at java.io.StringReader.<init>(StringReader.java:50)
        at com.google.gson.JsonParser.parse(JsonParser.java:45)
        at server.ServerProxy.gameList(ServerProxy.java:155)
        at server.ServerPoller$1.run(ServerPoller.java:48)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)
```
