### ISSUE TITLE
Placing settlement at desert hex in Second Round of game setup causes server crash.

### ISSUE THREAD

**Issue by jerekeith2** [cs340tabyu/cs340Winter2017#738]
Process:
1. Create new game leaving boxes unchecked.
2. Enter game with 4 non-AI players.
3. For first round of setup, place all roads in the middle of the map (see photo)
4. In the second round place road and settlement, where the settlement is on the desert hex with the robber (see photo).
5. Server will crash with the following error:

exception.InvalidMoveException: Player cannot build settlement at location
	at gamemodel.GameModel.buildSettlement(GameModel.java:1171)
	at server.ServerFacade.buildSettlement(ServerFacade.java:315)
	at shared.BuildSettlementCommand.execute(BuildSettlementCommand.java:24)
	at server.handler.BuildSettlementHandler.handle(BuildSettlementHandler.java:64)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
	at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:675)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:647)
	at sun.net.httpserver.ServerImpl$DefaultExecutor.execute(ServerImpl.java:158)
	at sun.net.httpserver.ServerImpl$Dispatcher.handle(ServerImpl.java:431)
	at sun.net.httpserver.ServerImpl$Dispatcher.run(ServerImpl.java:396)
	at java.lang.Thread.run(Thread.java:745)

<img width="1351" alt="screen shot 2016-11-18 at 2 28 40 pm" src="https://cloud.githubusercontent.com/assets/15175054/20447464/37e18174-ad9c-11e6-9b15-2366afecdb69.png">

**Comment by cojoco** [comment]
Fixed.
