### ISSUE TITLE
Server Error broke the game

### ISSUE THREAD

**Issue by jmango22** [cs340tabyu/cs340Winter2017#970]
```java.lang.NullPointerException
    at com.shared.command.UpdateGameStateCommand.executeServer(UpdateGameStateCommand.java:42)
    at com.server.CommandHandler.handle(CommandHandler.java:30)
    at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
    at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
    at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
    at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:675)
    at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
    at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:647)
    at sun.net.httpserver.ServerImpl$DefaultExecutor.execute(ServerImpl.java:158)
    at sun.net.httpserver.ServerImpl$Dispatcher.handle(ServerImpl.java:431)
    at sun.net.httpserver.ServerImpl$Dispatcher.run(ServerImpl.java:396)
    at java.lang.Thread.run(Thread.java:745)```

This error cause the game to crash

**Comment by blained3** [comment]
When did this happen? What did you do to get this? This is an unhelpful issue without this information.
